### ISSUE TITLE
[FR]: Intro to Bazel and Python could show more workflows

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/aspect-workflows-template#59]
### What is the current behavior?

https://www.youtube.com/playlist?list=PLLU28e_DRwdu46fldnYzyFYvSJLjVFICd

### Describe the feature

Doesn't show
- how to `./tools/ibazel run` the binary for hot-code-reload

**Comment by jab** [comment]
> how to ./tools/ibazel run the binary for hot-code-reload

has now been done - great video.

Before closing this, it would also be worth showing how to add a break point in vscode that actually gets hit when you “bazel run” or “test” a corresponding target.

**Comment by alexeagle** [comment]
I'm waiting on a fix before doing a video on editors. Probably also ran out of time to work on this freebie project, back to paid work...

**Comment by jab** [comment]
In case it's helpful, I took a hint from https://stackoverflow.com/a/72448621 and was able to get VSCode's Python Debugger working (so VSCode can hit breakpoints set via its UI when running the app via Bazel): https://github.com/jab/shorty/commit/d796dc8058dbb251eb4d39ad6f6ef6297300640f

<img width="2143" alt="Screenshot 2024-06-23 at 3 10 52 PM" src="https://github.com/aspect-build/aspect-workflows-template/assets/64992/d38745e8-88da-4140-bdbd-aa24c61974ea">


It's not the most seamless developer experience ever, but I think it's the best that can be done?

In addition to funding, curious what fix you're waiting for before doing a video on editors.

**Comment by alexeagle** [comment]
I'd like to debug a test as well, which means we need py_pytest_main generated. @jbedard has the change ready!
