### ISSUE TITLE
[FR]: bring in ruff via bzlmod

### ISSUE THREAD

**Issue by jab** [aspect-build/aspect-workflows-template#70]
### What is the current behavior?

[`fetch_ruff()` is called in WORKSPACE.bazel](https://github.com/aspect-build/aspect-workflows-template/blob/main/%7B%7B%20.ProjectSnake%20%7D%7D/WORKSPACE.bazel). Users (especially those who are new to Bazel) could find it confusing that this template sets up all dependencies in `MODULE.bazel` except for `ruff`, which is actually hiding in `WORKSPACE.bazel` (and there's no explanation about this discrepancy). Users may have heard that WORKSPACE files are deprecated and conclude they're getting set up with tech debt out-of-the-box, and may know they'll need to do to something to migrate once Bazel stops supporting WORKSPACE files, but not know what.

### Describe the feature

Remove `WORKSPACE.bazel` and pull in `ruff` via `MODULE.bazel`, so bzlmod is used exclusively, and there's only a single file where all dependencies are declared.

https://github.com/aspect-build/rules_lint/issues/279#issuecomment-2160983372 suggests this is possible using multitool.

**Comment by alexeagle** [comment]
This repo is following the install instructions for rules_lint, so any change belongs there first, FYI
